name: figure_payment_notification

on:
  schedule:
    # 毎月1日9:00に実行（UTC時間のため0 0 1に設定）
    - cron: '0 0 1 * *'
  workflow_dispatch: # 手動実行も可能

jobs:
  run-rake-task:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: production
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
    
    steps:
      # GithubActionsの仮想環境用のディレクトリにリポジトリのクローン
      - name: Checkout code
        uses: actions/checkout@v4

      # Rubyのセットアップ
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.10'
          bundler-cache: true

      # gemのインストール
      - name: Install dependencies
        run: bundle install

      # rakeタスクの実行
      - name: Run Update Payment Status
        run: bundle exec rake payment_status:update_payment_status